export const playerNames = [
  "KyuremRider",
  "ReshiramBlade",
  "DarkraiSlayer",
  "NACHONINJA",
  "OwenTheEevee",
  "zNycto",
  "SkwovetUwu",
  "idontknowuu",
  "Sw0le",
  "UN1VERSE",
  "iScrappyCoco",
  "Tony3145",
  "Tayhawk",
  "iCreatePlays",
  "GoopyBoo",
  "KanszerOFC",
  "LORD_GOOD",
  "jeffzin_FTS",
  "MOTA_N$",
  "Redxj",
  "Maudaraf",
  "Isaahse",
  "FAHYP",
  "tonycerk",
  "théo72",
  "poseidawn",
  "ManicPanic",
  "Majin_Mani",
  "ChronaKaori",
  "TheScotBot",
  "SetGent",
  "Mozzie",
  "cian",
  "Aoki",
  "Majestic_RAM",
  "TEODOR",
  "DoctorD0xy",
  "DarkRa3vn",
  "guipowered",
  "Katastry",
  "Amss19",
  "KostasA82",
  "Adam1sG1nger",
  "ca123",
  "ANTHONY247",
  "Omar34",
  "Aqollo",
  "Pyrus1035",
  "Poko",
  "Luffy",
  "Aura kills",
  "HoD • Andrés",
  "MR. PERFECT",
  "~TS×LORD°}~",
  "Wennin",
  "Mtro. Henry",
  "~TS×LORD°}",
  "Devil",
  "KOK • WOLF",
  "Luffu",
  "TEX • Haklon",
  "Angelo Mx",
  "Jay.",
  "RS • ProGsha",
  "Crystal moon",
  "DANGER PLAYZ:",
  "KGF",
  "Pìkàçhù",
  "BLACKSTAR",
  "Malayali",
  "GOAT",
  "GAMERS ESPORT",
  "Crystal",
  "Kaoz"
]
